### ISSUE TITLE
Crash on display illigal character

### ISSUE THREAD

**Issue by Hiroki3** [snowie2000/mactype#387]
When I open some text file included illegal characters (eg. 0xff 0xff 0xff 0xff 0xff 0xff 0xff 0xff...),
many applications crash. (notepad, Word, Excel, and other text editors)
Below is output of Event log:
(Hidemaru is a Japanese famous text editor.)

App Name on Error: Hidemaru.exe,Version: 8.7.5.99, Time Stamp: 0x59d5cd63
Module Name on Error: MacType64.Core.dll,Version: 1.2017.628.0,Time Stamp: 0x59532090
Exception code: 0xc0000005
Fault Offset: 0x000000000000a1c3
Process ID on Fault: 0x68c
App Start Time on Fault: 0x01d36976a9ca874e
App Path on Fault: C:\Program Files\Hidemaru\Hidemaru.exe
Module Path on Fault: C:\Program Files\MacType\MacType64.Core.dll
Report ID: 3ff9a19d-7a0e-4f5e-ae03-2537eb9a5d09

**Comment by snowie2000** [comment]
Please upload the text file, see if I can reproduce the problem. Thanks.

**Comment by Hiroki3** [comment]
Okay, here is illegal character text file attached.
[illigal.txt](https://github.com/snowie2000/mactype/files/1614492/illigal.txt)

**Comment by snowie2000** [comment]
Thanks, I'll try it.

**Comment by snowie2000** [comment]
So, I've tested this file on all my systems (US English), nothing happened, even with this Hidemaru editor (actually I used its English version as I can't read Japanese).
I think this problem may only happen with Japanese locale, and I'll try this later.

**Comment by Hiroki3** [comment]
This problem is solved when profile changed to others.
The profile which has trouble is 'default.ini', and I changed to 'LCD.ini' then problem is gone.
I don't identify what different point is affected to.
I attach these two profile.

[Default_and_LCD.zip](https://github.com/snowie2000/mactype/files/2190697/Default_and_LCD.zip)

**Comment by snowie2000** [comment]
Cool, thank you for pointing it out. I'll try it.

**Comment by snowie2000** [comment]
Ok, I tried, but it didn't crash. But, I still found the buggy code according to the crash you posted.
Stay tuned, and I'll upload a fix later today for you to try.

Thanks.

**Comment by snowie2000** [comment]
Here it is: [hotfix-for-ilegal-text.zip](https://github.com/snowie2000/mactype/files/2200851/hotfix-for-ilegal-text.zip)
Overwrite to your mactype folder and see if still crashes.

**Comment by Hiroki3** [comment]
Yeah, your fix has cleared my bug at all.
Even if FontLink=2, the annoying bug does not appear.
Thank you so much.

**Comment by snowie2000** [comment]
Thank you for your support. :+1:
